# docker-compose.yml

version: '3'

services:
  php-fpm:
    image: bfroger/popote-php-fpm:latest
    build:
      context: ./php
    depends_on:
      - database
    volumes:
      - ../src:/var/www
    environment:
      - MYSQL_ROOT_PASSWORD=bruno&
      - MYSQL_DATABASE=popote
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=popote&secret

  nginx:
    image: bfroger/popote-nginx:latest
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - database
      - php-fpm
    environment:
      - MYSQL_ROOT_PASSWORD=bruno&
      - MYSQL_DATABASE=popote
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=popote&secret

  database:
    image: bfroger/popote-database:latest
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=bruno&
      - MYSQL_DATABASE=popote
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=popote&secret
    volumes:
      #- ./database/popote_vide.sql:/docker-entrypoint-initdb.d/popote.sql
      - ./database/popote_latest.sql:/docker-entrypoint-initdb.d/popote.sql
